services:
  postgres:
    image: postgres:15-alpine
    container_name: banking-db
    environment:
      POSTGRES_DB: banking_db
      POSTGRES_USER: banking_user
      POSTGRES_PASSWORD: banking_pass
    ports:
    - "5433:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
